[package]
name = "nu_plugin_nutext"
version = "0.1.0"
edition = "2021"

[dependencies]
current_locale = "0.1.1"
gettext = "0.4.0"
locale-match = "0.2.2"
nu-plugin = "0.100.0"
nu-protocol = "0.100.0"
strfmt = "0.2.4"
tr = { version = "0.1.10", features = ["gettext"] }
